[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "4cbf7e384e768b4e01799441fdf2a706a5635ae7"

[[constraint]]
  name = "github.com/hashicorp/yamux"
  revision = "cc6d2ea263b2471faabce371255777a365bf8306"

[[constraint]]
  name = "github.com/mdlayher/vsock"
  revision = "7b7533a7ca4eba7dd23dab2de70e25ca6eecf7e2"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "f4982d86f7fde0b6f953cc62ccc4022c519a10a9"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "a1b50f621a48ad13f8f696a162f684a241307db0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "v1.4.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "87b1dfb5b2fa649f52695dd9eae19abe404a4308"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "2cbcf73e3dcdaa63941d0ec4008e69c089434756"

[[constraint]]
  name = "golang.org/x/net"
  revision = "a8b9294777976932365dabb6640cf1468d95c70f"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "ac767d655b305d4e9612f5f6e33120b9176c4ad4"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "d11072e7ca9811b1100b80ca0269ac831f06d024"

[[override]]
  name = "github.com/containerd/console"
  revision = "2748ece16665b45a47f884001d5831ec79703880"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.15.0"


[prune]
  non-go = true
  go-tests = true
  unused-packages = true
