[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "342cbe0a04158f6dcb03ca0079991a51a4248c02"

[[constraint]]
  name = "github.com/hashicorp/yamux"
  revision = "cc6d2ea263b2471faabce371255777a365bf8306"

[[constraint]]
  name = "github.com/mdlayher/vsock"
  revision = "738c88d6e4cfd60e8124a5344fa10d205fd828b9"

[[constraint]]
  name = "github.com/opencontainers/runc"
  revision = "cc4307ab6643668ce5abc6b524e1764a54c32550"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "5806c35637336642129d03657419829569abc5aa"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "f006c2ac4710855cf0f916dd6b77acf6b048dc6e"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "87b1dfb5b2fa649f52695dd9eae19abe404a4308"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "2cbcf73e3dcdaa63941d0ec4008e69c089434756"

[[constraint]]
  name = "golang.org/x/net"
  revision = "a8b9294777976932365dabb6640cf1468d95c70f"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "ac767d655b305d4e9612f5f6e33120b9176c4ad4"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "d11072e7ca9811b1100b80ca0269ac831f06d024"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
